=== Mosberg/minecraft-data-docs/schemas/nbt/spawner_nbt.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/Mosberg/minecraft-data-docs/tree/main/schemas/nbt/spawner_nbt.schema.json",
  "title": "Spawner NBT",
  "type": "object",

  "properties": {
    "SpawnData": {
      "type": "object",
      "additionalProperties": true
    },

    "SpawnCount": { "type": "integer" },
    "SpawnRange": { "type": "integer" },
    "RequiredPlayerRange": { "type": "integer" },
    "Delay": { "type": "integer" },
    "MinSpawnDelay": { "type": "integer" },
    "MaxSpawnDelay": { "type": "integer" },
    "MaxNearbyEntities": { "type": "integer" },

    "SpawnPotentials": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "data": { "type": "object" },
          "weight": { "type": "integer" }
        },
        "additionalProperties": true
      }
    }
  },

  "additionalProperties": true
}

=== Mosberg/minecraft-data-docs/examples/spawner_nbt/performance.json
{
  "Delay": 9999999,
  "MaxNearbyEntities": 9999999,
  "MaxSpawnDelay": 9999999,
  "MinSpawnDelay": 9999999,
  "RequiredPlayerRange": 9999999,
  "SpawnCount": 9999999,
  "SpawnData": {},
  "SpawnPotentials": [
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {}
  ],
  "SpawnRange": 9999999
}
